### ISSUE TITLE
move depends to imports

### ISSUE THREAD

**Issue by stanstrup** [lucanard/CCC#2]
When you make many dependencies it is better to only select the functions you want to use. Use the @importFrom in your roxygen code.

Build check also complains:

Depends: includes the non-default packages:
  'stringr' 'ppls' 'glmnet' 'fmcsR' 'rcdk' 'ChemmineR' 'metfRag'
Adding so many packages to the search path is excessive and importing
selectively is preferable.

EDIT: also even if you have packages in depends they need to be imported. That's why build check complains about all functions basically.

**Comment by lucanard** [comment]
I did it.
Thanks Jan
